import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Status, Wrapper} from "@googlemaps/react-wrapper";
import Map from "../components/Map";
import {getAlerts} from "../database/Connector";

export default function Home({local_alerts, global_alerts}) {
    const render = (status) => {
        switch (status) {
            case Status.LOADING:
                return <h1>Loading...</h1>;
            case Status.FAILURE:
                return <h1>Error, please try again.</h1>;
            case Status.SUCCESS:
                return <Map alerts={local_alerts}/>;
        }
    };

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <Wrapper apiKey={process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY} render={render} />
            </main>
        </div>
    )
}

export async function getStaticProps() {
    // Fetch data from external API
    let res = await getAlerts();
    res = res.map(packet => {return {...packet}})
    console.log(res)

    // Pass data to the page via props
    return {
        props: { local_alerts: res },
        revalidate: 360, // In seconds
    }
}
